[alias]
"@src/*" = "./src/*"
"@clients/*" = "./src/clients/*"
"@boot/*" = "./src/boot/*"
"@connectors/*" = "./src/connectors/*"
"@serialization/*" = "./src/serialization/*"
"@types" = "./src/types/index.ts"
"@types/*" = "./src/types/*"
"@wallet/*" = "./src/wallet/*"
